#include "stdafx.h"
#include ".\backlogindlg.h"

// LRESULT CBackLoginDlg::OnEnChangeEditParam(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/)
// {
// 	// TODO:  If this is a RICHEDIT control, the control will not
// 	// send this notification unless you override the CDialogImpl<CBackLoginDlg>::OnInitDialog()
// 	// function and call CRichEditCtrl().SetEventMask()
// 	// with the ENM_CHANGE flag ORed into the mask.
// 
// 	// TODO:  Add your control notification handler code here
// 
// 	return 0;
// }
